Line.create(content: "白い砂浜の海岸で見つけた貝殻を")
Line.create(content: "漆黒の海に投げた")
Line.create(content: "あの日の風は確かに")
Line.create(content: "君の頬を撫でていたのさ")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "おいでおいでよ今すぐに抜け出しておいで")
Line.create(content: "灰色の教室の窓の外から")
Line.create(content: "おいでおいでよ今すぐに抜け出しておいで")
Line.create(content: "群青の空に今日も月が輝く")
Line.create(content: "Uh Uh Uh(コーラス)")
Line.create(content: "夏の青い空の白い雲に")
Line.create(content: "すいかの赤がにじんだ")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "おいでおいでよ今すぐに抜け出しておいで")
Line.create(content: "")
Line.create(content: "おいでおいでよ今すぐに抜け出しておいで")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "なぜ時は悲しみをつれてくる")
Line.create(content: "なぜ沈黙は何よりも愛を語る")
Line.create(content: "")
Line.create(content: "黄金の庭のみえる部屋で")
Line.create(content: "君と夕食のテーブルで話そう")
Line.create(content: "")
Line.create(content: "")
Line.create(content: "おいでおいでよ今すぐに抜け出しておいで")
Line.create(content: "")
Line.create(content: "おいでおいでよ今すぐに抜け出しておいで")
Line.create(content: "群青の空に今日も星が輝く")
Line.create(content: "Uh Uh Uh(コーラス)")
Line.create(content: "Uh Uh Uh(コーラス)")



